name: forms360_uikit
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.5.7
  go_router: ^14.3.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  riverpod_generator: ^2.4.0
  riverpod_annotation: ^2.3.5
  drop_down_search_field: ^1.0.5
  flutter_otp_text_field: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^4.0.0
  test: ^1.24.0
