enum PermissionType {
  CLIENTS,
  PROFILE,
  USERS,
  ACTIVITY_LOGGER,
  ANNOUNCEMENTS,
  INDUSTRY_PACKAGE,
  DASHBOARD_SYSTEM_REPORTS,
  DASHBOARD_BUSINESS_REPORTS,
}

enum PermissionOptionsType { CREATE, UPDATE, READ, DELETE }
